# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
  tracking_id : 'UA-42866277-1'
  getclicky :
  site_id :


author :
  name : Innovatt - Inovação e tecnologia
  #github : caarlos0
  twitter : innovat_t
  email: leandronardo@innovatt.com.br
