permalink: /posts/:title
#rdiscount:
#  extensions: [smart]
title : Innovatt - Inovação e tecnologia
production_url : http://blog.innovatt.com
#description: "Througths, flamewars, utilities, tutorials, codes, projects."
disqus_shortname: innovatt



# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics : UA-42866277-1
  #provider : google
  #google : 
  #tracking_id : ''
  #getclicky :
  #site_id :


author :
  name : Innovatt - Inovação e tecnologia
  #github : caarlos0
  twitter : innovat_t
  email: leandronardo@innovatt.com.br
  
  
  
